### ISSUE TITLE
[Bug] The mouse cursor doesn't change to pointer when hovering over the Cart link

### ISSUE THREAD

**Issue by utkarsh1311** [itsnitinr/nextjs-shopping-cart#2]
The mouse cursor should change to pointer when hovering over the Cart link in the navbar and some other css styling also doesn't work. 
It works for the Home and Shop links though.
![Screenshot from 2022-08-03 00-35-46](https://user-images.githubusercontent.com/70108561/182453701-100828de-06ad-4be2-9592-b304959bd076.png)

**Comment by itsnitinr** [comment]
Thanks for reporting @utkarsh1311 

Would you like to open a PR to fix this issue?

**Comment by utkarsh1311** [comment]
Yes. Please assign it to me.
